### ISSUE TITLE
Provide documentation for the code

### ISSUE THREAD

**Issue by Giulero** [ivanbergonzani/binarized-neural-network#2]
Hello!

Can you provide a [description](https://github.com/ivanbergonzani/binarized-neural-network/blob/master/README.md) for your project?

Lo dico a @micco00x  e ti sculaccia da parte mia!

**Comment by micco00x** [comment]
Yep, it should be updated with https://github.com/micco00x/NeuralNetworksReport.

**Comment by micco00x** [comment]
Closed with 6de8a1c5b99efd769937150e5e30a2362d24cde5.
